language: java
jdk:
  - openjdk8
  - openjdk9
script:
  - jdk_switcher use openjdk9
  - mvn clean install

jobs:
  include:
  -stage: Test
  script: mvn clean test

notifications:
  email: prateek.kumar@triconinfotech.com
